### PR TITLE
Update LCD character display block to support different I2C addresses

### PR DESCRIPTION
**Pull request by sk8board**
Issue https://github.com/BIPES/BIPES/issues/227 shows the LCD block only supports LCD's that have 0x27 I2C address.

Updated the LCD character display block to support different I2C addresses.

Changes have been verified with Pi Pico and ESP32.

### CODE REVIEW

**Comment by jetannenbaum** [comment]
Seems like a very large change to the esp32.xml file and no update to the rpi_pico.xml or rpi_pico_w.xml file.  This update will break all other micro controllers.  Not sure the other I2C address choices need to be added at this time, since it might confuse the casual user.  If you want them all in, then make the two common ones as the first two choices in the drop down.

**Comment by jetannenbaum** [comment]
I found this chunk of code in one of the libraries that is floating around for the display:
    def scanAddress(self, addr):
        devices = self.bus.scan()
        if len(devices) == 0:
            raise Exception("No LCD found")
        if addr is not None:
            if addr in devices:
                return addr
            else:
                raise Exception(f"LCD at 0x{addr:2X} not found")
        elif 0x27 in devices:
            return 0x27
        elif 0x3F in devices:
            return 0x3F
        else:
            raise Exception("No LCD found")
Note that this library only accepts the two cI2C address cases.  Perhaps the drop down is sufficient to have only two choices at this time.

**Comment by sk8board** [comment]
> Seems like a very large change to the esp32.xml file and no update to the rpi_pico.xml or rpi_pico_w.xml file. This update will break all other micro controllers. Not sure the other I2C address choices need to be added at this time, since it might confuse the casual user. If you want them all in, then make the two common ones as the first two choices in the drop down.

The changes to the esp32.xml file were to update these files to the same level as the Pico for the LCD related blocks. Since you were maintaining only Pico related code, I assumed the esp32.xml file was many updates behind. The current state of the ESP32 LCD block is broken because the library load button is incorrect. My changes to esp32.xml were needed to make ESP32 work with the current LCD block, not this change. Please compare the LCD display blocks between ESP32 and Pico at their current state, then I believe you will see what I am describing. 

The original code MicroPython code only supported 0x27 I2C address. This change uses 0x27 as the default address to ensure previous users will have a seamless user experience. 

As for limiting to only two addresses in the dropdown menu, I do not recommend this limitation. There are many addresses for LCD's. For example, Adafruit does not use 0x27, but uses 0x3C, 0x3D, 0x3E, and 0x3F. I imagine there are other manufacturers using even other addresses. 

If you would like, I could add code to scan and print all of the I2C addresses that are being used at the time of code operation? This would alert the user, in the console, to make informed  attempts of available addresses. 

Let me know your thoughts. I appreciate your support.

**Comment by sk8board** [comment]
It seems you would like to limit the scope of this LCD code block to the library. This make sense and is quite reasonable. 

With that said, even the PCF8574 interface chip can be configured to 8 different addresses and the PCF8574A to another 8 different addresses. The address can be permanently set by the LCD board designer to the address of their choice. Or, some LCD board designs allow the user to configure the address with solder jumper pads as shown on my LCD (A0, A1, A2).

Are you sure you want to limit to only two addresses?

image

image

image

image

image

IMG_20240409_114408_658

By the way, SparkFun has their Quiic product line of I2C components that have an all in one Python library for all the Quiic components. These components have software adjustable I2C addresses.

https://www.sparkfun.com/qwiic

https://github.com/sparkfun/Qwiic_SerLCD_Py?tab=readme-ov-file

**Comment by sk8board** [comment]
I added a note to the block to show the block only supports PCF8574. Does this look appropriate to you?


image

**Comment by sk8board** [comment]
image

**Comment by jetannenbaum** [comment]
I understand that the boards are programmable.  But, I think those are the edge cases.  Will the average person, just starting out, buy a board with a "non-default" I2C address?  Some of the libraries will reject a board that doesn't use one of the two standard addresses.  That said, I don't object to the way you show the drop down.  It has the defaults as the primary selections, so it accomplishes the objective of making the base addresses easy to find and select.    

Nit picky here: I would change the text on the init block to reflect the existing text in the navigation section such that it reads "with the PCF8574 Display Controller"

image

**Comment by sk8board** [comment]
> Nit picky here: I would change the text on the init block to reflect the existing text in the navigation section such that it reads "with the PCF8574 Display Controller"
>

I do not consider this being nit picky. I provided a screenshot to ensure alignment.

Does this look appropriate to you?

image

**Comment by jetannenbaum** [comment]
The pull request looks good.  Merged.  Thanks for your continuing efforts to improve BIPES

**Comment by sk8board** [comment]
> I'd like to think about the Sparkfun aspect that you raised a little further. Assuming I'm reading the specs properly, the Sparkfun QWIIC interface is designed for a processor running Python, not MicroPython. Not sure how to support those boards without finding a port of the Sparkfun libraries to either MicroPython 9preferred) or Circuit Python (we would have to add something like Blinka (https://learn.adafruit.com/circuitpython-libraries-on-micropython-using-the-raspberry-pi-pico)

Looks like SparkFun is currently developing MicroPython libraries for Quiic.

https://github.com/orgs/sparkfun/projects/24

**Pull request merged**
